### ISSUE TITLE
For with nested if

### ISSUE THREAD

**Issue by elfet** [coderhaoxin/gulp-file-include#106]
Got error on this:

```
      @@for (var i in ARRAY) {
        @@if (i !=='') {
          <link href="@@i">
        }
      }
```

**Comment by mishingo** [comment]
Im in the same boat

**Comment by huangwentai** [comment]
do you fixed yet , i find way like this ,and it work

@@for (var i = 0; i < breadcrumb.length; i++) {
					<li class="breadcrumb-item `+ breadcrumb[i].active +`">
						`+ ((breadcrumb.length!=i+1)?('<a href="#">' +breadcrumb[i].name+ '</a>'):breadcrumb[i].name) +`
					</li>
				}

<li class="breadcrumb-item "><a href="#">參數</a></li>
<li class="breadcrumb-item active">系統參數</li>
