### ISSUE TITLE
How can I add a parameter to a variable?

### ISSUE THREAD

**Issue by JacobDB** [coderhaoxin/gulp-file-include#125]
I'm trying to set up a custom variable that will automatically convert over to an SVG. The format would be:

    @@icon("search")

Which would output:

    <svg class="svg-icon"><use xlink:href="#search" /></svg>

Is this possible to do with this module, or no?

**Comment by richardtallent** [comment]
I'm a newbie at using this library (just started tonight), but I'm not aware of any mechanism for creating custom functions. However, I think you could accomplish what you want with a template:

**svg.html**
`<svg class="svg-icon"><use xlink:href="#@@link" /></svg>`

**input.html**
`@@include('./svg.html',{"link":"search"})`

The syntax is a little longer, but it would produce the output you want.

Another option would be to use `gulp-replace`, which allows simple regex search and replace, so you could replace something terse (say, `<svg:search>`) with the expanded markup you want.

**Comment by JacobDB** [comment]
Ah, thanks, that's useful info! I'll give it a try when I have a few spare minutes.

**Comment by JacobDB** [comment]
@richardtallent I finally got around to trying this, and I figured it out. Works perfectly :)

`.pipe(replace(/(?:<icon:)([^>]+)(?:>)/g, "<i class='fa fa-$1' aria-hidden='true'><\/i>"))`

(Note that I'm currently using FontAwesome but plan to change this to SVG at some point in the future...)

Thanks much!
