### ISSUE TITLE
How to check the existence of a variable?

### ISSUE THREAD

**Issue by nicothin** [coderhaoxin/gulp-file-include#139]
I want to check the existence of a variable in the attached file. If a variable was transferred to the file when it was included, output some part of the markup.
How to do it?

**Comment by angeliquejw** [comment]
You can do this by calling your include like so :
`@@include(FILEPATH, { "foo": "bar" })`

And then, in your include, using an `@@if` statement, like so:
`@@if (context.foo === 'bar') { YOURMARKUPHERE }`

I'm doing this now for a site to pass an "is-active" class to my site navigation. :)

**Comment by nicothin** [comment]
`@@if (context.testVar) { YOURMARKUPHERE }`
excellent! It's almost what I wanted.
Only one thing: it's not checking the existence of a variable, it's checking that the type of the variable === true (if bring it to a boolean) :)
