### ISSUE TITLE
Support to variables

### ISSUE THREAD

**Issue by tarciozemel** [coderhaoxin/gulp-file-include#2]
I believe gulp-file-include would be a lot more usefull with support to variables. So, for example, would be possible to include a `header.inc` defining value of properties to the tags. Something like:

``` html
index.html

@@include("/path/to/include/header.inc", { "description" : "My cool web site" })
<h1>My site</h1>
@@include("/path/to/include/footer.inc")
```

``` html
header.inc

<!doctype html>
<html>
    <header>
        [...]
        <meta name="description" value="@@description">
        [...]
```

**Comment by macr** [comment]
+1 being able to pass variable to the root template would be really cool.

**Comment by TrySound** [comment]
In new release it will be able.
