### ISSUE TITLE
Parsing of @@include() fails without trailing newline

### ISSUE THREAD

**Issue by troywarr** [coderhaoxin/gulp-file-include#25]
I'm using an `@@include()` within a Jade template. My gulpfile renders the template into HTML, then includes within that HTML output a separate rendered HTML file containing some SVG elements.

Because Jade minifies its HTML output, the result is something like this excerpt:

    ... //]]></script>@@include('./icons/svg/symbols.svg')<!--[if lt IE 9]><p class="browsehappy">You are using an <strong>outdated</strong> browser. ...

This causes gulp to throw the following error:

    stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
    Error: ENAMETOOLONG, name too long '/Users/twarr/code/lockstep.info/dist/)<!--[if lt IE 9]><p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http:/browsehappy.com/" target="_blank">upgrade your browser</a> to improve ...

It appears that gulp-file-include doesn't notice that the `@@include()` ends after the closing parenthesis, and instead expects a newline character. Adding one to my Jade template fixed it:

    | @@include('./icons/svg/symbols.svg')
    = "\n"

Ideally, though, that wouldn't be required. It seems like the closing parenthesis should be enough for the regular expression to determine that the `@@include()` has ended, and thus have enough information to parse out the include file path, regardless of what immediately follows. Please let me know if that assumption is incorrect, though.

Thanks!

**Comment by TrySound** [comment]
No fail for now.
Close?

**Comment by coderhaoxin** [comment]
@TrySound yes, it works in most cases. But it's hard to fix in some edge cases.

not care too much about that. :smile: close... for now.
