### ISSUE TITLE
Conditional include with variables

### ISSUE THREAD

**Issue by TrySound** [coderhaoxin/gulp-file-include#27]
Hi!
What if you would do conditional include with variables, not just arguments:

```
@@include('tmp.html', {"nav": true})
```

```
@@if(nav) {
    @@include('nav.html')
}
```

P.S.
In documentation a little mistake. "If" with just one "@"

**Comment by DanielTate** [comment]
I can confirm this is still not working.My example is exactly that of @TrySound

**Comment by coderhaoxin** [comment]
@DanielTate yes, this is not working for now

**Comment by coderhaoxin** [comment]
0.8.0 published!
