### ISSUE TITLE
suffix option

### ISSUE THREAD

**Issue by TrySound** [coderhaoxin/gulp-file-include#28]
Sometimes need to hide include constructions from html by comments.
Can you add suffix option like in [grunt-include-replace](https://github.com/alanshaw/grunt-include-replace)?

**Comment by coderhaoxin** [comment]
consider to use [meta-templater](https://github.com/TrySound/meta-templater) as a dep.

**Comment by TrySound** [comment]
Good. You may open issue for some corrections or ideas.

**Comment by coderhaoxin** [comment]
2a67d07463d82ca95389e6edfb4bd82a1e65ee93
