### ISSUE TITLE
meta-templater

### ISSUE THREAD

**Issue by TrySound** [coderhaoxin/gulp-file-include#30]
Hey! Happy New Year!

I created meta API based on syntax of your `gulp-file-include`. Let's make some improvements?
https://github.com/TrySound/meta-templater

**Comment by coderhaoxin** [comment]
@TrySound 
I'll take a look ASAP!

**Comment by TrySound** [comment]
I made refactoring. Now it's more stable.

**Comment by coderhaoxin** [comment]
merge to #28
