### ISSUE TITLE
Smart File Include

### ISSUE THREAD

**Issue by TrySound** [coderhaoxin/gulp-file-include#32]
Add option with default file extensions. Maybe array or string.
Process file error with gulp-util.log
And cut the root from file path in error report

And make a few search paths (base paths) for flexible structure

**Comment by coderhaoxin** [comment]
> Add option with default file extensions. Maybe array or string.

Is this really need?

`some/one/two/a.html`, `some/one/two/a` not a big difference.

> make a few search paths (base paths) for flexible structure

maybe, something like this

.
+-- /home/me
|  +-- /files
|  +-- /templates
|  +-- /myapp
|    +--/gulpfile.js
|    +--/files
|      +--a.html

```js
// set optional paths
var paths = ['/home/me/files', '/ome/me/templates']

// @@include('b.html') will try to get file data from
'/home/me/myapp/files/b.html';
'/home/me/myapp/b.html';
'/home/me/files/b.html';
''/ome/me/templates/b.html'
```

similar to `require`?

**Comment by TrySound** [comment]
Okey, no need.

Maybe @root, @file and added relative (from root) paths.
