### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by TrySound** [coderhaoxin/gulp-file-include#34]
When including file doesn't exist gulp takes off. And I have to use gulp-plumber. It's bad.

So, I recommend you to use for exceptions `throw new gutil.PluginError(pluginName, message);` (`new` necessarily) and to check file existance with `fs.existsSync(filename);`

**Comment by TrySound** [comment]
Hm.. it's strange.

Sometimes gulp catches an errors, sometimes crashes in:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: recursion detected in file: D:\_host\githost\gulp-file-include\example\index.txt
```

Maybe problem is in gulp itself.

Error exception in your code no need to replace. It's good for now. I just replaced event-stream with through2 in pull request.

**Comment by coderhaoxin** [comment]
maybe relate to other plugins.

**Comment by TrySound** [comment]
No, I use just include for html

**Comment by web2style** [comment]
Gulp-plumber catches errors, but it doesn't point to the file where the error occurred, for ex.:

```
[14:52:14] Plumber found unhandled error:
 Error in plugin 'gulp-file-include'
Message:
    active is not defined
```

Any way to know the file with the error? Sometimes it is almost impossible to find it manually.

**Comment by zanettin** [comment]
+ 1
