### ISSUE TITLE
Stream handling

### ISSUE THREAD

**Issue by TrySound** [coderhaoxin/gulp-file-include#36]
You don't need to handle streams, because text is small thing. And parsing a part of construction is not good, bacause it will be missed or errored.

What do you think?

**Comment by coderhaoxin** [comment]
> And parsing a part of construction is not good, bacause it will be missed or errored.

yes, but no mind for that.

**Comment by TrySound** [comment]
I will delete it, ok?

**Comment by coderhaoxin** [comment]
just keep it.
