### ISSUE TITLE
Jade templates included file wrong spacing

### ISSUE THREAD

**Issue by stoplion** [coderhaoxin/gulp-file-include#37]
How do you include a Jade (or any template language) with this library and keep the correct white space? [File is being included correctly, but white space is wrong.](http://stackoverflow.com/questions/28018899/gulp-file-include-and-jade-nesting-problems)

**Comment by TrySound** [comment]
file-include does not response for your indents,
You can save firstline empty and then use indent based of the parent template. I don't know is it good for Jade.

**Comment by coderhaoxin** [comment]
I'll add a test for this, `white space` should be included correctly.

**Comment by TrySound** [comment]
@coderhaoxin It's correctly, but parent indents are not inherited.

**Comment by coderhaoxin** [comment]
> but parent indents are not inherited.

yes, it should

**Comment by TrySound** [comment]
Need to pass third argument in include with parent information.

It could be useful for error tracing. I will realize this in [MT](//github.com/trysound/meta-templater).

**Comment by coderhaoxin** [comment]
@TrySound +1

**Comment by bradgreens** [comment]
@stoplion I solved a similar problem with Jade, but it was messy. http://stackoverflow.com/a/29043553/845717.

@TrySound should I open an issue regarding `gulp-file-include`'s ability to support multiple includes on the same line? If my slim templates compile the `@@` directives to the following HTML can we make it "just work"?
```
@@include('./dist/templates/_header.html')@@include('./dist/templates/_nav.html')
```

**Comment by TrySound** [comment]
I think this must work in Meta-templater. I will test this ASAP

**Comment by TrySound** [comment]
@bradgreens It's works!

**Comment by TrySound** [comment]
@coderhaoxin let's make a list of meta-templater requirements for using it as dependancy

**Comment by TrySound** [comment]
@bradgreens I made some fixes in parser. Try it again, please.

**Comment by TrySound** [comment]
@stoplion I added indent option. You can try it with jade.
