### ISSUE TITLE
if condition not working

### ISSUE THREAD

**Issue by thetutlage** [coderhaoxin/gulp-file-include#38]
```
@@include("../partials/footer.html",{"page":"index"})
```

And instead footer.html i have 

```lang-html
@@if (page === "index"){
    @@include('./appstore.html')
 }
@@if (page !== "index"){
  @@include('./newsletter.html')
}
```
It says page is not defined

**Comment by coderhaoxin** [comment]
:cry: because they are not in the same file. 

so, `page` is not defined.

**Comment by thetutlage** [comment]
If i am passing something to the include , that should to be passed to the include file , isn't it ?

**Comment by TrySound** [comment]
@coderhaoxin Meta templater fix this:-)

**Comment by thetutlage** [comment]
@TrySound  What is Meta templater ??

**Comment by TrySound** [comment]
@thetutlage [my parser](https://github.com/TrySound/meta-templater) for this syntax

**Comment by dirkluijk** [comment]
Same issue over here. Seems like the variable was not passed to the included file.

**Comment by robbinjanssen** [comment]
@coderhaoxin Is there a roadmap or an estimated date for 1.0.0? :)

**Comment by coderhaoxin** [comment]
before April :cry:

**Comment by robbinjanssen** [comment]
@coderhaoxin thanks, I can live with that, great work you're doing here! Might look at some alternatives in the meantime. Primarily use it to (conditionally) merge markdown files.

**Comment by bewards** [comment]
I would love to see this in action soon as well. If you declare the variable in the context option, it works, but there's definitely a need to have that variable page based.

**Comment by svkarpovich** [comment]
@@if works correctly if add next code at line 152
```
text = parseConditionalIncludes(text, variables);
```

**Comment by sarguvlad** [comment]
@svkarpovich, that line is already [there](http://joxi.ru/8238jJMUDkjGAO), but that doesn't change anything, or you meant something else?

**Comment by svkarpovich** [comment]
@sarguvlad, Currently this code on line 154. Try to duplicate this line and paste to line 152.

**Comment by TrySound** [comment]
Reference on #62.
This issue could be closed.

**Comment by ShahidH** [comment]
Is it fixed yet? 

I get an error:  `is not defined`

**Comment by minlare** [comment]
@ShahidH - see #84 

You need to check the variable on `context` object as follows:

```
@@if (context.myVar) {
  @@myVar
}
```

**Comment by shakercs** [comment]
{
          "stackedCards": {
          "image": "/images/section2.svg",
          "orderNum": "54674567"          }},

@@if (context.stackedCards.image) {
   //test
}
    Cannot read property 'image' of undefined:  (context.stackedCards.image) 

not working with me
