### ISSUE TITLE
Multiple locations for files

### ISSUE THREAD

**Issue by jovpet** [coderhaoxin/gulp-file-include#40]
Is there an option to use multiple file locations? for example my structure is:
-- /app
|  -- /components
|     --header.html
|  -- /files
|     --logo.svg
|  -- /pages
|     --home.html

And I want to include in pages/page.html components/header.html and files/logo.svg
I hvae my gulp task:

```javascript
gulp.task('include', function() {
  gulp.src(['app/pages/*.html'])
    .pipe(fileinclude({
      prefix: '@@',
      basepath: ['./app/files/', './app/components/']
    }))
    .pipe(gulp.dest('./app'));
});
```

but once I run it it says:
**Error: Arguments to path.resolve must be strings**

Can I use multiple folders for base paths?

**Comment by TrySound** [comment]
For now no. In the next release it will be able.
And #32

**Comment by raphaelgoetter** [comment]
+1 Would be great !

**Comment by TrySound** [comment]
#70

**Comment by mrtdeh** [comment]
+1

**Comment by arekuusa** [comment]
+1
