### ISSUE TITLE
Error for combination of symbols in value

### ISSUE THREAD

**Issue by tslater** [coderhaoxin/gulp-file-include#41]
When I do something like:
```
			@@include('summaryList.html', {
				"variable": "function({paraneter:7})"
			})
```

I get:
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Unexpected end of input
```

It seems to be the combination of the parenthesis and the curly brackets. Is there a way to escape those characters? Is it trying to execute them as javascript?

**Comment by TrySound** [comment]
No way. But [meta-templater](https://github.com/trysound/meta-templater) works fine with it.

**Comment by tslater** [comment]
Why am I even getting this error?

**Comment by TrySound** [comment]
Because file-include use regexp for parsing.

**Comment by TrySound** [comment]
Referenced on #63

**Comment by TrySound** [comment]
@tslater Try this now

**Comment by coderhaoxin** [comment]
closing for now. reopen if the bug still exists!
