### ISSUE TITLE
Retain folder structure from scanned directories

### ISSUE THREAD

**Issue by stagfoo** [coderhaoxin/gulp-file-include#47]
This might just be me because im new to gulp but is there an `option` to retain the dir structure when creating render html files?
```
Working Folder
______
--/cwd
---/includes
---/templates
----/layouts
------(default.html)

```
This currently render to (which i dont want)
```
Results
______
--/render
---(default.html)

```
the structure i would like is

```
Results
______
--/render
---/templates
----/layouts
------(default.html)
```

**Comment by TrySound** [comment]
It's a gulp issue https://github.com/gulpjs/gulp/blob/master/docs/API.md
Look at base option
