### ISSUE TITLE
Can't import htmls with different parameters

### ISSUE THREAD

**Issue by norbikaa** [coderhaoxin/gulp-file-include#48]
For example:
@@include("block-list", {
	"title1": "title1",
	"title2": "title2"
})
@@include("block-list", {
	"title1": "title1"
})
Result:
title1 title2
title1 @@title2

If I use the If statement
@@include("block-list", {
	"title1": "title1",
	"title2": "title2"
})
@@include("block-list", {
	"title1": "title1"
})

and the block-list content:
@@if (typeof title1 != "undefined") { @@title1 }
@@if (typeof title2 != "undefined") { @@title2 }

the result is same:
title1 title2
title1 @@title2

In my opinion if input a html then input that again (with other parameters), the values don't reset, only inherit.

**Comment by norbikaa** [comment]
Found a solution:
@@if (text == "@text") {
      @@text
}

But I don't understand why work this...

**Comment by jwbaart** [comment]
Experiencing a similar issue when executing the following code:

@@include("block-list", {
"title": "title1"
})
@@include("block-list", {
"title": "title2"
})

block-list content:
@@title
@@if (title === 'title1') {
    // Do something for 1
} @@if (title === 'title2') {
    // Do something for 2
}

Result:
title1
// Do something for 2
title2
// Do something for 2

Thus when calling the same include with different parameters, it will use the last known parameters for every include.

**Comment by TrySound** [comment]
Reference on #62.
This issue could be closed.
