### ISSUE TITLE
Includes within includes?

### ISSUE THREAD

**Issue by lasseyls** [coderhaoxin/gulp-file-include#49]
Is it possible to have a template.html like:
```
<article id="@@variable">
    @@include("./partials/@@variable.html")
</article>
```
and then have something outside like:

        @@include('./partials/template.html', {
            "variable": "some_other_template"
        })

**Comment by TrySound** [comment]
You may do this
```
<article id="@@variable">
    @@include("./partials/" + variable + ".html")
</article>
```
It's just a variable :-)

**Comment by teej043** [comment]
@TrySound 

It doesn't seem to work for me.
gulp-file-include v 0.9.0

~~~
  @@include("../demo/block-module.html",{
    "content" : "block-module-one"
  })
~~~

~~~
<div class="block">
  <div class="@@content">
    @@include("../demo/" + content + ".html")
  </div>
</div>
~~~

the output html displays:

@@include('../demo/' + content + '.html')

**Comment by TrySound** [comment]
@coderhaoxin

**Comment by coderhaoxin** [comment]
Not supported for now.

**Comment by coderhaoxin** [comment]
Add to todo list of `v1.0.0`, shame on such a long delay for `v1.0.0` :cry:

**Comment by TrySound** [comment]
Reference on #62.
This issue could be closed.

**Comment by karneaud** [comment]
Is there any workaround?
