### ISSUE TITLE
Passing in objects into include?

### ISSUE THREAD

**Issue by jpbullalayao** [coderhaoxin/gulp-file-include#53]
Hello! 

This is a question. I have the following code:

![screen shot 2015-04-21 at 2 40 34 pm](https://cloud.githubusercontent.com/assets/3538024/7263222/96a4de24-e834-11e4-9118-9b3e3b6096ae.png)

As you can see, I'm gonna use a "name" variable in `site-nav.html`. Is there anyway I can use some kind of JavaScript object instead rather than hardcode the variables in every single file? Something like:

```
<script>
    var obj = { "name": "Jourdan" }
</script>
@@include('./site-nav.html', obj)
```

**Comment by coderhaoxin** [comment]
Sorry, `NO`.

**Comment by TrySound** [comment]
@coderhaoxin context doesn't work?

**Comment by coderhaoxin** [comment]
https://github.com/coderhaoxin/gulp-file-include#if-statement

@TrySound `context` is defined at gulpfile, not every single file

**Comment by TrySound** [comment]
@coderhaoxin Ok.

**Comment by TrySound** [comment]
@coderhaoxin I made new version of [my parser](https://github.com/TrySound/meta-templater/tree/1.0)

**Comment by coderhaoxin** [comment]
@TrySound :v:

**Comment by TrySound** [comment]
This issue could be closed.
