### ISSUE TITLE
If else

### ISSUE THREAD

**Issue by web2style** [coderhaoxin/gulp-file-include#55]
`class="@@if (active === 'index') {index}"` works fine, but how can I have `else` condition also?

`class="@@if (active === 'index') {index} else {inner}"` throws error, `class="@@if (active === 'index') {index} @@else {inner}"` also.

**Comment by coderhaoxin** [comment]
+1

**Comment by TrySound** [comment]
@web2style You can use negative condition for it.

**Comment by web2style** [comment]
@TrySound Could you please provide an example? I tried
```class="@@if (active === 'index') {index} @@if (active !== 'index') {inner}"```
but it also throws an exception.

**Comment by TrySound** [comment]
@web2style Which exception it throws?

**Comment by web2style** [comment]
@TrySound 
```events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unexpected token {

**Comment by TrySound** [comment]
@web2style Looks like javascript syntax error. Check your code.

**Comment by web2style** [comment]
But it disappears when I change this line to `class="@@if (active === 'index') {index}`

**Comment by TrySound** [comment]
@web2style Perheps it's regexp problem.
Try this
```
@@if (active === 'index') {<span class="index">}
@@if (active === 'index2') {<span class="index-2">}
```

**Comment by web2style** [comment]
@TrySound It works like this, but I can't use it for class declaration, because an element can't have 2 classes.

@coderhaoxin So this looks like a bug.

**Comment by TrySound** [comment]
@web2style At next friday we will start to discuss integrating of my [meta-templater](https://github.com/trysound/meta-templater) as an engine. It parses without regular expression, so will be more stable.

**Comment by TrySound** [comment]
@web2style You can try this. And ask questions in gitter room

**Comment by coderhaoxin** [comment]
0.12.0
