### ISSUE TITLE
Indentation is not maintained

### ISSUE THREAD

**Issue by mlenser** [coderhaoxin/gulp-file-include#58]
When including a HTML file the resulting file does not have the same indentation as the base file. All the nesting is broken.

Perhaps this is due to CRLF?

**Comment by TrySound** [comment]
@mlenser I think the only first line is parent indent + current indent. I just leave the first line empty. Or you can use some html beautifiers.

**Comment by mlenser** [comment]
@TrySound Oooh, first line blank is a better solution than my extra spacing to make it work. Thanks!

**Comment by mlenser** [comment]
This is merely a workaround, not a solution..

**Comment by TrySound** [comment]
@mlenser Don't think so. It's a task for another gulp plugin.

**Comment by mlenser** [comment]
Your stance is that your code should require another plugin to create properly indented html?

**Comment by TrySound** [comment]
@mlenser It's the node way. Small module is doing one mission. Together they are doing the world.

**Comment by TrySound** [comment]
@mlenser I added this feature.
