### ISSUE TITLE
Source map support

### ISSUE THREAD

**Issue by stephanedemotte** [coderhaoxin/gulp-file-include#60]
[gulp-sourcemap](https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support) support can be awesome !

**Comment by sdaitzman** [comment]
:+1: I really want this :yum:

**Comment by TrySound** [comment]
@sdaitzman Where do you use it?

**Comment by sdaitzman** [comment]
A lasercutter/CNC queuing system, open source @ https://github.com/yrsegal/LaserQueue

**Comment by TrySound** [comment]
Which language? Just interesting.

**Comment by sdaitzman** [comment]
We use gulp-file-include to process frontend JS, but the backend is python 3

**Comment by TrySound** [comment]
browserify is not case?

**Comment by sdaitzman** [comment]
I looked into browserify and it would work too but I like the simplicity this gives me

**Comment by TrySound** [comment]
This feature will be realized not so soon. Sorry. I have no much time and firstly need to fix parser.

**Comment by sdaitzman** [comment]
That's alright! Thanks for the tool anyway.

**Comment by TrySound** [comment]
#70
