### ISSUE TITLE
Redefined variables

### ISSUE THREAD

**Issue by igoradamenko** [coderhaoxin/gulp-file-include#62]
I have some htmls:

header.html:

	<header class="header">
		@@include('../backcall/backcall.html', { 
			"parent": "header__backcall"
		})
	</header>

backcall.html:

	<div class="backcall @@parent">
		@@include('../icon/icon.html', { 
			"parent": "backcall__icon"
		})
	</div>

icon.html:

	<span class="icon @@parent"></span>

Aafter compilation I get:

	<header class="header">
		<div class="backcall backcall__icon">  
			<span class="icon backcall__icon"></span>
		</div>
	</header>

`parent` is redefined in backcall.html. So I think it's a bug :)

**Comment by TrySound** [comment]
@igoradamenko I work on this problem.

**Comment by coderhaoxin** [comment]
@TrySound collaborator added. Also npm

**Comment by TrySound** [comment]
@igoradamenko @thetutlage @norbikaa Check this out. I think it fixed.

**Comment by igoradamenko** [comment]
@TrySound yes, it works perfectly now. thanks!

**Comment by norbikaa** [comment]
@TrySound Tested and works perfectly. This fix saved my life :dancers:
