### ISSUE TITLE
use @@if and @@include with a param

### ISSUE THREAD

**Issue by RazvanDH** [coderhaoxin/gulp-file-include#64]
```  
@@if(this.env==='production') {
    @@include('partials/google-analytics.html.tpl', {"ua": "XXXXXXX"})
}
```
will output the correct partial, with the parameter in place, but it also outputs the `@@if` condition

**Comment by TrySound** [comment]
@RazvanDH What output when codition is false.

**Comment by RazvanDH** [comment]
@TrySound, first of all, thanks for the really quick reply. 

It's the same output with the condition true / false. It considers `@@if` as being a string. It's something to do with the curly braces I think (I know there's another issue with something similar).

**Example:**

```
// consider this.env === 'production'
@@if(this.env==='production') { {lipsum} }
@@if(this.env==='production') { lipsum }
```
*will output:*
```
@@if(this.env==='production') {{lipsum}}
lipsum
```

```
// consider this.env !== 'production'
@@if(this.env==='production') { {lipsum} }
@@if(this.env==='production') { lipsum }
```
*will output:*
```
@@if(this.env==='production') {{lipsum}}
```

Hope this helps.

**Comment by TrySound** [comment]
@RazvanDH Yes. Nested curly braced doesn't work. It's regexp. I will rewrite a little consition parser today. So tomorrow you will be able use it.

**Comment by RazvanDH** [comment]
Thanks @TrySound. That's great news.

**Comment by TrySound** [comment]
@RazvanDH You can use fix-cond branch instead of npm module as a dependency.
```
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-file-include": "git://github.com/coderhaoxin/gulp-file-include.git#fix-cond",
    "gulp-rename": "^1.2.2"
  }
```

**Comment by coderhaoxin** [comment]
0.12.0

**Comment by TrySound** [comment]
@RazvanDH Done!

**Comment by RazvanDH** [comment]
@TrySound - thanks for the fast fix, man. Will check it on Monday.
