### ISSUE TITLE
Optional indent detecting

### ISSUE THREAD

**Issue by TrySound** [coderhaoxin/gulp-file-include#66]
Suggest to add boolean `indent` option
`Include` parser will calculate indent from start of construction. If there is no one non-space char beetwen newline and start then move each line of included content.
It could be minor change.
@coderhaoxin Do you agree?

**Comment by coderhaoxin** [comment]
I'm +1 for this. Just make the default option: `indent: false`

**Comment by TrySound** [comment]
@coderhaoxin Sure. I agree with it.
