### ISSUE TITLE
Missing index.js

### ISSUE THREAD

**Issue by mondalaci** [coderhaoxin/gulp-file-include#68]
Just ran `npm install gulp-file-include` and inside of `node_modules/gulp-file-include` there was no `index.js`. I reproduced this on two host, one from Hungary and the other from London. What can be the problem?

**Comment by mondalaci** [comment]
Just checked that 0.12.0 seems ok but 0.13.0 doesn't.

**Comment by TrySound** [comment]
@mondalaci Try again, please. Published 0.13.1

**Comment by TrySound** [comment]
@mondalaci 0.13.2

**Comment by mondalaci** [comment]
Works great, thanks!
