### ISSUE TITLE
Implementing 'gulp-file-include' in 'yeoman/generator-gulp-webapp'

### ISSUE THREAD

**Issue by MsTrends** [coderhaoxin/gulp-file-include#69]
I'm using [yeoman/generator-gulp-webapp][1] and I've added [gulp-file-include][1] plugin. I've generated vanilla `gulpfile.babel.js` by using yeoman, now i'm able to implement file-include command within 'html' task and with 'gulp html' command i'm able to compile html files correctly,
but I'm not sure how to implement file-include plugin in this file (gulpfile.babel.js) in such a way that it works with `gulp serve` seamlessly.

I've tried to implement it with no luck. Following is the code from my `gulpfile.babel.js` file:

    // generated on 2015-07-07 using generator-gulp-webapp 1.0.2
    import gulp from 'gulp';
    import gulpLoadPlugins from 'gulp-load-plugins';
    import browserSync from 'browser-sync';
    import del from 'del';
    import {stream as wiredep} from 'wiredep';
    
    const $ = gulpLoadPlugins();
    const reload = browserSync.reload;
    
    gulp.task('styles', () => {
      return gulp.src('app/styles/*.scss')
        .pipe($.plumber())
        .pipe($.sourcemaps.init())
        .pipe($.sass.sync({
          outputStyle: 'expanded',
          precision: 10,
          includePaths: ['.']
        }).on('error', $.sass.logError))
        .pipe($.autoprefixer({browsers: ['last 1 version']}))
        .pipe($.sourcemaps.write())
        .pipe(gulp.dest('.tmp/styles'))
        .pipe(reload({stream: true}));
    });
    
    function lint(files, options) {
      return () => {
        return gulp.src(files)
          .pipe(reload({stream: true, once: true}))
          .pipe($.eslint(options))
          .pipe($.eslint.format())
          .pipe($.if(!browserSync.active, $.eslint.failAfterError()));
      };
    }
    const testLintOptions = {
      env: {
        mocha: true
      },
      globals: {
        assert: false,
        expect: false,
        should: false
      }
    };
    
    gulp.task('lint', lint('app/scripts/**/*.js'));
    gulp.task('lint:test', lint('test/spec/**/*.js', testLintOptions));
    
    gulp.task('html', ['styles'], () => {
      const assets = $.useref.assets({searchPath: ['.tmp', 'app', '.']});
    
      return gulp.src('app/*.html')
        .pipe(assets)
        .pipe($.if('*.js', $.uglify()))
        .pipe($.if('*.css', $.minifyCss({compatibility: '*'})))
        .pipe(assets.restore())
        .pipe($.useref())
        .pipe($.if('*.html', $.fileInclude({prefix: '@@', basepath: '@file'})))
        .pipe($.if('*.html', $.minifyHtml({conditionals: true, loose: true})))
        .pipe(gulp.dest('dist'));
    });
    
    gulp.task('images', () => {
      return gulp.src('app/images/**/*')
        .pipe($.if($.if.isFile, $.cache($.imagemin({
          progressive: true,
          interlaced: true,
          // don't remove IDs from SVGs, they are often used
          // as hooks for embedding and styling
          svgoPlugins: [{cleanupIDs: false}]
        }))
        .on('error', function (err) {
          console.log(err);
          this.end();
        })))
        .pipe(gulp.dest('dist/images'));
    });
    
    gulp.task('fonts', () => {
      return gulp.src(require('main-bower-files')({
        filter: '**/*.{eot,svg,ttf,woff,woff2}'
      }).concat('app/fonts/**/*'))
        .pipe(gulp.dest('.tmp/fonts'))
        .pipe(gulp.dest('dist/fonts'));
    });
    
    gulp.task('extras', () => {
      return gulp.src([
        'app/*.*',
        '!app/*.html'
      ], {
        dot: true
      }).pipe(gulp.dest('dist'));
    });
    
    gulp.task('clean', del.bind(null, ['.tmp', 'dist']));
    
    gulp.task('serve', ['styles', 'fonts'], () => {
      browserSync({
        notify: false,
        port: 9000,
        server: {
          baseDir: ['.tmp', 'app'],
          routes: {
            '/bower_components': 'bower_components'
          }
        }
      });
    
      gulp.watch([
        'app/*.html',
        'app/scripts/**/*.js',
        'app/images/**/*',
        '.tmp/fonts/**/*'
      ]).on('change', reload);
    
      gulp.watch('app/styles/**/*.scss', ['styles']);
      gulp.watch('app/fonts/**/*', ['fonts']);
      gulp.watch('bower.json', ['wiredep', 'fonts']);
    });
    
    gulp.task('serve:dist', () => {
      browserSync({
        notify: false,
        port: 9000,
        server: {
          baseDir: ['dist']
        }
      });
    });
    
    gulp.task('serve:test', () => {
      browserSync({
        notify: false,
        port: 9000,
        ui: false,
        server: {
          baseDir: 'test',
          routes: {
            '/bower_components': 'bower_components'
          }
        }
      });
    
      gulp.watch('test/spec/**/*.js').on('change', reload);
      gulp.watch('test/spec/**/*.js', ['lint:test']);
    });
    
    // inject bower components
    gulp.task('wiredep', () => {
      gulp.src('app/styles/*.scss')
        .pipe(wiredep({
          ignorePath: /^(\.\.\/)+/
        }))
        .pipe(gulp.dest('app/styles'));
    
      gulp.src('app/*.html')
        .pipe(wiredep({
          exclude: ['bootstrap-sass'],
          ignorePath: /^(\.\.\/)*\.\./
        }))
        .pipe(gulp.dest('app'));
    });
    
    gulp.task('build', ['lint', 'html', 'images', 'fonts', 'extras'], () => {
      return gulp.src('dist/**/*').pipe($.size({title: 'build', gzip: true}));
    });
    
    gulp.task('default', ['clean'], () => {
      gulp.start('build');
    });

  [1]: https://github.com/yeoman/generator-gulp-webapp

**Comment by TrySound** [comment]
@MsTrends gulp-load-plugins use camelcase for hyphen-separated names. So use should use $.fileInclude instead.

**Comment by MsTrends** [comment]
@TrySound Yeah, i just realized this mistake, now i'm unable to make it work with 'gulp serve' command.

**Comment by TrySound** [comment]
@MsTrends What's problem? These tasks are independent.

**Comment by MsTrends** [comment]
Yeah, they are independent. But even if i add 'html' in 'gulp serve' task like this:

     gulp.task('serve', ['html', 'styles', 'fonts'], () => {

html files are not being compiled, I'm not sure how to integrate file-include plugin within this task in such a way that it can work with 'browserSync' plugin.

**Comment by TrySound** [comment]
I think the problem could be if gulp.if. Or not))
You also can use `require('main-bower-files')('**/*.js')` without object.

**Comment by MsTrends** [comment]
I'm sorry i didn't understand what you are trying to say. I've tracked a previous ticket regarding 'browserSync' here: https://github.com/coderhaoxin/gulp-file-include/issues/51

And i think my problem is very similiar to this, i've also tried your mentioned suggestion (i.e. adding .pipe(reload({ stream: true  })); to the end of html task), but it is of no use.

Currently, uncompiled .html files are in 'app' folder and what i've understood that these files must be compiled to '.tmp' folder (on 'gulp serve' command) in order to see the effect as '.tmp' folder has precedence over app, as described here: https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/README.md#serve

**Comment by TrySound** [comment]
@MsTrends It's just not the problem of plugin. What exactly doesn't work in you case?

**Comment by MsTrends** [comment]
When we run 'gulp serve' command, it'll create a live local url to the production site (e.g. http://localhost:9000/), now if i change any file (.scss, .js etc excluding .html) in 'app' folder it's effect will automatically appear in browser windows without refreshing the page. Now, i want file-include plugin to behave in the same way (i.e. change in any .html file in 'app' folder should immediately appear in the webpage on http://localhost:9000/), currently i'm can only see uncompiled code in borwser, something like this:

        @@include('navigation.html')

**Comment by TrySound** [comment]
@MsTrends Sorry, I don't see any decisions. You may create smallest example. And research its.
Then maybe I will find something.

**Comment by MsTrends** [comment]
Thanks, very much for your time and assistance, I was able to solve the issue by following this tutorial, together with some changes: https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/jade.md

**Comment by TrySound** [comment]
@MsTrends Nice!

**Comment by jpiemeisl** [comment]
MsTrends, can you post your updated gulpfile.babel.js file? I'm having a similar issue using the yeoman generator. Did you switch over to jade or did you update the way you're using gulp-file-include?

**Comment by MsTrends** [comment]
No, I didn't switch over to jade rather I modified my gulpfile as per the instructions given at the link above and modified it as per my requirement. My gulpfile is below:

<pre>
// generated on 2015-07-07 using generator-gulp-webapp 1.0.2
import gulp from 'gulp';
import gulpLoadPlugins from 'gulp-load-plugins';
import browserSync from 'browser-sync';
import del from 'del';
import {stream as wiredep} from 'wiredep';

const $ = gulpLoadPlugins();
const reload = browserSync.reload;

gulp.task('styles', () => {
  return gulp.src('app/styles/*.scss')
    .pipe($.plumber())
    .pipe($.sourcemaps.init())
    .pipe($.sass.sync({
      outputStyle: 'expanded',
      precision: 10,
      includePaths: ['.']
    }).on('error', $.sass.logError))
    .pipe($.autoprefixer({browsers: ['last 1 version']}))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});

function lint(files, options) {
  return () => {
    return gulp.src(files)
      .pipe(reload({stream: true, once: true}))
      .pipe($.eslint(options))
      .pipe($.eslint.format())
      .pipe($.if(!browserSync.active, $.eslint.failAfterError()));
  };
}
const testLintOptions = {
  env: {
    mocha: true
  },
  globals: {
    assert: false,
    expect: false,
    should: false
  }
};

gulp.task('lint', lint('app/scripts/**/*.js'));
gulp.task('lint:test', lint('test/spec/**/*.js', testLintOptions));

gulp.task('views', function () {
  return gulp.src('app/*.html')
    .pipe($.fileInclude({ prefix: '@@', basepath: '@file' }))
    .pipe(gulp.dest('.tmp'))
    .pipe(reload({stream: true}));
});

gulp.task('html', ['views', 'styles'], () => {
  const assets = $.useref.assets({searchPath: ['.tmp', 'app', '.']});

  return gulp.src(['app/*.html', '.tmp/*.html'])
    .pipe(assets)
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', $.minifyCss({compatibility: '*'})))
    .pipe(assets.restore())
    .pipe($.useref())
    .pipe($.if('*.html', $.minifyHtml({conditionals: true, loose: true})))
    .pipe(gulp.dest('dist'));
});

gulp.task('images', () => {
  return gulp.src('app/images/**/*')
    .pipe($.if($.if.isFile, $.cache($.imagemin({
      progressive: true,
      interlaced: true,
      // don't remove IDs from SVGs, they are often used
      // as hooks for embedding and styling
      svgoPlugins: [{cleanupIDs: false}]
    }))
    .on('error', function (err) {
      console.log(err);
      this.end();
    })))
    .pipe(gulp.dest('dist/images'));
});

gulp.task('fonts', () => {
  return gulp.src(require('main-bower-files')({
    filter: '**/*.{eot,svg,ttf,woff,woff2}'
  }).concat('app/fonts/**/*'))
    .pipe(gulp.dest('.tmp/fonts'))
    .pipe(gulp.dest('dist/fonts'));
});

gulp.task('extras', () => {
  return gulp.src([
    'app/*.*',
    '!app/*.html',
    '!app/partials/*.html'
  ], {
    dot: true
  }).pipe(gulp.dest('dist'));
});

gulp.task('clean', del.bind(null, ['.tmp', 'dist']));

gulp.task('serve', ['views', 'styles', 'fonts'], () => {
  browserSync({
    notify: false,
    port: 9000,
    server: {
      baseDir: ['.tmp', 'app'],
      routes: {
        '/bower_components': 'bower_components'
      }
    }
  });

  gulp.watch([
    'app/*.html',
    '.tmp/*.html',
    'app/scripts/**/*.js',
    'app/images/**/*',
    '.tmp/fonts/**/*'
  ]).on('change', reload);

  gulp.watch('app/**/*.html', ['views']);
  gulp.watch('app/styles/**/*.scss', ['styles']);
  gulp.watch('app/fonts/**/*', ['fonts']);
  gulp.watch('bower.json', ['wiredep', 'fonts']);
});

gulp.task('serve:dist', () => {
  browserSync({
    notify: false,
    port: 9000,
    server: {
      baseDir: ['dist']
    }
  });
});

gulp.task('serve:test', () => {
  browserSync({
    notify: false,
    port: 9000,
    ui: false,
    server: {
      baseDir: 'test',
      routes: {
        '/bower_components': 'bower_components'
      }
    }
  });

  gulp.watch('test/spec/**/*.js').on('change', reload);
  gulp.watch('test/spec/**/*.js', ['lint:test']);
});

// inject bower components
gulp.task('wiredep', () => {
  gulp.src('app/styles/*.scss')
    .pipe(wiredep({
      ignorePath: /^(\.\.\/)+/
    }))
    .pipe(gulp.dest('app/styles'));

  gulp.src('app/partials/*.html')
    .pipe(wiredep({
      exclude: ['bootstrap-sass'],
      ignorePath: /^(\.\.\/)*\.\./
    }))
    .pipe(gulp.dest('app'));
});

gulp.task('build', ['lint', 'html', 'images', 'fonts', 'extras'], () => {
  return gulp.src('dist/**/*').pipe($.size({title: 'build', gzip: true}));
});

gulp.task('default', ['clean'], () => {
  gulp.start('build');
});

</pre>

**Comment by Theminijohn** [comment]
Thanks @MsTrends, Works well !

**Comment by Theminijohn** [comment]
Thanks @MsTrends, Works well ! However when `gulp build` runs it does not compile the templates. Any Idea why ?

**Comment by brunoaugustocom** [comment]
Thanks for sharing the gulpfile. I was with the same issue and your solution helped me a bunch. Greetings!

**Comment by mandalatv** [comment]
While the above gulpfile inserted includes on gulp serve, it kept giving me the following error while I attempted a gulp build (with generator-gulp-webapp 1.0.4):

<code>TypeError: $.useref.assets is not a function</code>

I modified the html task to include the fileInclude() call rather than pass views as an argument, and now it works on both serve and build for me. 

<pre><code>
gulp.task('html', ['styles'], () => {
  return gulp.src('app/*.html')
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', $.cssnano()))
    .pipe($.if('*.html', $.htmlmin()))
    .pipe($.if('*.html', $.fileInclude({prefix: '@@', basepath: '@file'})))
    .pipe(gulp.dest('dist'));
});
</code></pre>

**Comment by razinbunsu** [comment]
Thank you!
