### ISSUE TITLE
onSuccess and onError handlers?

### ISSUE THREAD

**Issue by Jakobud** [coderhaoxin/gulp-file-include#71]
Is there a way to do a callback when the include is successful or if there is an error?

**Comment by TrySound** [comment]
@Jakobud Why you need it? Stream fires `error` when something fail.

**Comment by Jakobud** [comment]
Sorry I'm new to gulp. Can you explain where it would go?

```
gulp.task('html', function(){
	return gulp.src(['html/index.html'])
		.pipe($.fileInclude({
			prefix: '@@',
			basepath: '@file'
		}))
		.pipe(gulp.dest('.'));
});
```

**Comment by TrySound** [comment]
On error it will break stream, If you use watchers you can do this
```
gulp.task('html', function(done){
    return gulp.src(['html/index.html'])
        .pipe($.fileInclude({
            prefix: '@@',
            basepath: '@file'
        }))
        .on('error', done)
        .pipe(gulp.dest('.'));
});
```
This will catch an error and won't stop you watcher.

**Comment by Jakobud** [comment]
Oh geez I never new you could do that with gulp. Thanks,
