### ISSUE TITLE
gulp-file-include support global context?

### ISSUE THREAD

**Issue by ihaolin** [coderhaoxin/gulp-file-include#72]
Hello，I am using **gulp-file-include** to organize my html views，the **context** option is used to **if** statement according to document，but can the **context** is used in any html file? that say，I define an attribute in **fileinclude**，and use it in html。

Thanks & Regards

**Comment by TrySound** [comment]
@ihaolin It's a small conflict.

`context` in options is global variable. They works with @@var syntax and in conditionals

`context` in conditionals is an object with globals and locals. It could be useful if variable is unnecessary:

This will fail if param is undefined
```
@@if(param === 'value') {}
```

This will work fine.
```
@@if(context.param === 'value') {}
```

**Comment by ihaolin** [comment]
Thanks，I use **@@var** to solve my problem。
