### ISSUE TITLE
For Loops Support within Templates

### ISSUE THREAD

**Issue by jzhang300** [coderhaoxin/gulp-file-include#73]
Is there a way to loop through an array within the templates?

If I want to pass in an array of say 20-50 elements, I don't want to manually type all items in.

**Comment by 7immy** [comment]
This would be good!! :)
I can imagine a syntax like below...
```
@@include('./var.html',{
    "name": myData.name,
    "age": myData.age
}).each('data.json', {data: "myData"})
```
The each function has 2 arguments:
 1. For the file location 
 2. For loop configuration

**Comment by TrySound** [comment]
@jzhang300 This feature will be in 1.0 version. In future. Not sure soon.
@7immy It's not simple construction. This will be better
```
@@each([{ }]) {
  @@include('./var.html',{
    "name": data.name,
    "age": data.age
  })
}
```

**Comment by 7immy** [comment]
@TrySound Brilliant news! I was just helping the conversation along to get people interested but it seems there is no need!

Cheers :)

**Comment by 7immy** [comment]
Would external database sources such as files be included in this feature?

**Comment by TrySound** [comment]
@7immy You will be able to write own handlers for `function` (like include) or `operator` (like if).

**Comment by TrySound** [comment]
#70

**Comment by jzhang300** [comment]
@7immy 
@TrySound 

Thanks for being so fast to respond!

One suggestion is to do it like Jade's iteration syntax: http://jade-lang.com/reference/iteration/
I think having access to the index value is really important.

**Comment by PierBover** [comment]
Has this been implemented?

**Comment by webarthur** [comment]
### `loop`
index.html

```
@@loop('loop-article.html', [
	{ "title": "My post title", "text": "<p>lorem ipsum...</p>" },
	{ "title": "Another post", "text": "<p>lorem ipsum...</p>" },
	{ "title": "One more post", "text": "<p>lorem ipsum...</p>" }
])

```

loop-article.html
```html
<article>
	<h1>@@title</h1>
	@@text
</article>

```

Check in my git: https://github.com/webarthur/gulp-file-include

**Comment by PierBover** [comment]
Awesome @webarthur !

**Comment by LeaVerou** [comment]
Do I *have* to use a separate template? Can I not do it inline? It seems pointless to have separate templates for like 1 line bits of HTML, just because `@@loop` needs it.

Thanks for a great plugin!

**Comment by yairEO** [comment]
Like others have said here, I want to be able to include a bunch of templates, by supplying a rule:

````
@@loopInclude('../html-includes/[FILENAME].html', [
    'login', 
    'forgot-password', 
    'reset-password',
    'expired', 
    'email-sent'
  ])
````

I imagine it working like the above example
