### ISSUE TITLE
Missing file throws error that shuts down gulp

### ISSUE THREAD

**Issue by kirillbunin** [coderhaoxin/gulp-file-include#74]
I'm using gulp-file-include in a "watch". Which is problematic, since errors about missing files terminates the process.

**Comment by TrySound** [comment]
It's not plugin problem. Streams do not support error bubbling. You can use this
```
gulp.task(function (done) {
  gulp.src()
    .pipe(include())
    .on('error', done)
    .pipe(gulp.dest('dist'))
});
```
This will good work with every plugin that throws an error.

**Comment by kirillbunin** [comment]
Learning by making mistakes, the way i like it.
Thank you!

**Comment by TrySound** [comment]
@kirillbunin It's not very popular way, but it works better another one.
