### ISSUE TITLE
Not equal to operator in IF statement

### ISSUE THREAD

**Issue by MsTrends** [coderhaoxin/gulp-file-include#75]
I'm unable to use 'not equal to' operator in if statement. For example in following code, test.html file is still being included even if 'nav' variable is set to false.

<pre>
@@include('some.html', { "nav": false})
</pre>

and in 'some.html' file ...

<pre>
@@if (nav !== false) {
  @@include('test.html')
}
</pre>

**Comment by TrySound** [comment]
Show your gulpfile

**Comment by MsTrends** [comment]
This is the related code from gulp file.

gulp.task('views', function () {
  return gulp.src('app/*.html')
    .pipe($.fileInclude({ prefix: '@@', basepath: '@file'}))
    .pipe(gulp.dest('.tmp'))
    .pipe(reload({stream: true}));
});

**Comment by TrySound** [comment]
@MsTrends In your example first include and if in different files?

**Comment by MsTrends** [comment]
It's actually a simplified version from this plugin's Readme.md file. 'nav' variable is being passed to 'some.html' file and the if statement itself is in 'some.html' file.

**Comment by TrySound** [comment]
Does it throw an error?

**Comment by MsTrends** [comment]
Nope, no error in terminal. It simply ignores the condition and include the 'test.html' file.

**Comment by TrySound** [comment]
I tried this, but it works fine.

**Comment by MsTrends** [comment]
It seems the example mentioned above is not exactly depciting my situation. In my example above, variable is being passed to only one file 'some.html', but in my actual code it's being passed to two files one by one. For example:

in first file ...

<pre>
@@include('some.html', { "nav": false})
</pre>

in 'some.html' file ...

<pre>
@@include('some-other.html', { "nav": "@@nav"})
</pre>

and now in 'some-other.html' file. This condition doesn't work.

<pre>
@@if (nav !== false) {
  @@include('test.html')
}
</pre>

Although, i can get 'nav' variable value in 'some-other.html' file but it's not being working in IF condition.

**Comment by TrySound** [comment]
@MsTrends `false` isn't equal `"false"`, so...

**Comment by MsTrends** [comment]
Yes, for this reason i already tried using ...

<pre>
@@if (nav !== 'false') {
  @@include('test.html')
}
</pre>

but it shows the same result.

**Comment by TrySound** [comment]
Actually variables apply after includes. So I think nav is equal `"@@nav"`

**Comment by MsTrends** [comment]
No, if in 'some-other.html' file i print this variable value like so:

<pre>
<p>@@nav</p>
</pre>

It prints 'false' (without quotes), so the value of variable is fine. It just not working in IF statement either with or without quotes.

**Comment by TrySound** [comment]
Try this
```
@@if (console.log(nav)) {
}
```

**Comment by MsTrends** [comment]
Yeah, now it's printing @@nav in terminal. But on front-end it shows original value.

**Comment by TrySound** [comment]
@MsTrends It's includes with @@nav value and then this value replaces with variables.

**Comment by TrySound** [comment]
I will swap includes and variables parsing in a hour.

**Comment by MsTrends** [comment]
That's strange as same variable gives two different values based on context (i.e. used in IF statement OT simply being printed using @@nav). Does such swapping will fix this issue?

**Comment by TrySound** [comment]
@MsTrends Yes. It's just bubbling like behaivour. Variables processes all files with already included partials.

**Comment by MsTrends** [comment]
Ok. Thanks very much for your support, I'll be waiting for the update.

**Comment by TrySound** [comment]
Fixed with 0.13.6
Thanks.

**Comment by MsTrends** [comment]
Yes, I can confirm. Issue is resolved now.
