### ISSUE TITLE
 Include only the path to the file, not its contents (Question)

### ISSUE THREAD

**Issue by thiagoaag** [coderhaoxin/gulp-file-include#83]
Hello!
first, congratulation for this awesome tool.
and so ....
i would include only the path to the file, not its contents.
is there any setting for this?

**Comment by coderhaoxin** [comment]
> i would include only the path to the file, not its contents

Could you give an example?

**Comment by thiagoaag** [comment]
yes!
for example:
 @@include('./js/home.js')

will result:
 <script type="text/javascript" src="./js/home.js"></script>

**Comment by TrySound** [comment]
@thiagoaag You will be able to do custom functions in 1.0

**Comment by thiagoaag** [comment]
thanks!
