### ISSUE TITLE
If / else with params

### ISSUE THREAD

**Issue by anstaks** [coderhaoxin/gulp-file-include#84]
Hello! Is it possible to use something like:
```
@@include('blocks/b-breadcrumbs/b-breadcrumbs.html', {
    "name": "Reliable payment solution for online game developers"
})
```
in b-breadcrumbs.html I have:
```
<h1>
@@if (@@name) {
    @@name
} else {
     Default header
}
</h1>
```

I can't find that feature(((.

**Comment by TrySound** [comment]
@anstaks else won't be realized. Use `@@if(cond) {}` `@@if(!cond)`

**Comment by anstaks** [comment]
@TrySound I see, it's not problem, but I can't set correct conditions, gulp falling! Can you write correct conditions for my example? Thank you!

**Comment by TrySound** [comment]
@anstaks Can you show your code and error log?

**Comment by anstaks** [comment]
@TrySound 
```
@@if (@@name) {
    @@name
}
```

Error in plugin 'gulp-file-include'
Message:
    Unexpected token ILLEGAL

If I set 
```
        @@if ("name") {
          @@name
        }
```
Contidion return always true...

**Comment by TrySound** [comment]
You should use non-prefixed variables in if statement

**Comment by TrySound** [comment]
```
@@if (name) {
    @@name
}
```

**Comment by anstaks** [comment]
@TrySound I was try...
```
@@if (name) {
    @@name
}
```

Error in plugin 'gulp-file-include'
Message:
    name is not defined

**Comment by TrySound** [comment]
@anstaks Okay. Do you pass this variable somewhere?

**Comment by anstaks** [comment]
@TrySound Yes, that variable exist in one view, but it does not exist in other views. In other views I want to put default header.

**Comment by TrySound** [comment]
@anstaks 
```
@@if (context.name) {
    @@name
}
```

**Comment by anstaks** [comment]
@TrySound 
Error in plugin 'gulp-file-include'
Message:
    contex is not defined

My variable I set in view, not in Gulpfile.js

**Comment by TrySound** [comment]
@anstaks `context`, not `contex`
context in if statement is not global variables, it's object with all variables in this view.

**Comment by anstaks** [comment]
Ohhh... I got mistake, "contex" instead "context"

**Comment by anstaks** [comment]
It Works! Thank you very much! Спасибо ;-)!

**Comment by TrySound** [comment]
@anstaks Expression in if statement is javascript

**Comment by TrySound** [comment]
@anstaks You are welcome.

**Comment by shakercs** [comment]
> @anstaks
> 
> ```
> @@if (context.name) {
>     @@name
> }
> ```

thank you so much ,but it's not working with multi level json like 

{
    "stackedCards": {
    "image": "/images/section2.svg",
    "orderNum": "54674567"
    }}, 

@@if (context.stackedCards.image) {
   //test
}

**Comment by sdebanik** [comment]
@@for (var i = 0; i < data.length; i++) {
  @@if ( JSON.parse('`+data[i].include_file+`') == true ) {
          //do something
    }
 }
 
 @TrySound This is never working. Any thing I am missing or has issues in Gulp
 inlcude itself

**Comment by sdebanik** [comment]
Okkkkkk , I found the solution

@@for (var i = 0; i < data.length; i++) {
    @@if ( `+context.data[i].checked === true +` ) {
          @@include(`+data[i].something+`)
      }
}

It WORKED!! :)
