### ISSUE TITLE
js file include js file

### ISSUE THREAD

**Issue by riyue** [coderhaoxin/gulp-file-include#94]
js file include js file , can't work
i really want to use this way

**Comment by TrySound** [comment]
@riyue Show your code.

**Comment by riyue** [comment]
file a.js
`(function(){
  @@include('b.js')
})();`

file b.js
`var a=1;`

then can i get a.js like this
`(function(){
  var a=1;
})();`

**Comment by TrySound** [comment]
@riyue And what you get now? Do you have errors?

**Comment by riyue** [comment]
file a.js
(function(){ @@include('b.js') })();

file b.js
var a=1;

i want to get this
(function(){ var a=1; })();
but get this now,no errors, it can't be convert. 
(function(){ @@include('b.js') })();

**Comment by riyue** [comment]
it's my falut, it works。my path is wrong。
by the way。
path like this。
/include/a.js
/src/b.js    @@include('include/a.js')     i want to write absolute path relative to gulp path

so how to write the path  fileinclude({
          prefix: '@root',
          basepath: '@file'
        }
it can't work, this output @@include('include/a.js')

**Comment by riyue** [comment]
it's my falut, it works。my path is wrong。
