### ISSUE TITLE
Using with gulp-changed

### ISSUE THREAD

**Issue by prestyman** [coderhaoxin/gulp-file-include#96]
Is there any way to use gulp-file-include with gulp-changed, so that it only builds those files that will be changed in the stream?

**Comment by TrySound** [comment]
@prestyman gulp-changed can't help with such small tasks. Text files are not so big.

**Comment by prestyman** [comment]
using the function hasChanged with the built-in comparator changed.compareSha1Digest works. 

`gulp.task('fileinclude', function() {
  return gulp.src('DEV/**/*.{html,htm,php}')
    .pipe(changed('BUILD', {hasChanged: changed.compareSha1Digest})) //make fileinclude only process those files that will change
    .pipe(fileinclude())
    .pipe(gulp.dest('BUILD'));
});`

**Comment by TrySound** [comment]
@prestyman gulp-changed can't know if dependency of this html was changed.

**Comment by prestyman** [comment]
Actually it can.  By using the changed.compareSha1Digest, it can compare the file's content SHA1 hash.  So when watching the directory, if you make a change to an include file it will run the task fileinclude task ONLY on those files that actually use the include. This is my full gulpfile.js:
```javascript
var gulp = require('gulp');
var changed = require('gulp-changed');
var fileinclude = require ('gulp-file-include');

gulp.task('content', function() {
  return gulp.src('DEV/**/*.html')
  .pipe(changed('BUILD'))
  .pipe(fileinclude())
  .pipe(gulp.dest('BUILD'));
});

gulp.task('fileinclude', function() {
  return gulp.src('DEV/**/*.html')  
    .pipe(changed('BUILD', {hasChanged: changed.compareSha1Digest}))
    .pipe(fileinclude())
    .pipe(gulp.dest('BUILD'));
});

gulp.task('default', ['content'], function() {
  gulp.watch('DEV/**/*.html', ['content']);
  gulp.watch('DEV/**/*.inc', ['fileinclude']);
});
'

**Comment by TrySound** [comment]
Okay.
