### ISSUE TITLE
Can't change variable prefix

### ISSUE THREAD

**Issue by Hargat** [coderhaoxin/gulp-file-include#97]
It will be good staf to change prefix by default for variables

**Comment by TrySound** [comment]
So change it. What's wrong?

**Comment by Hargat** [comment]
Well it's suggestion, I will not able to commit some changes

**Comment by TrySound** [comment]
@Hargat Why you don't like default? Is it too difficult for you to specify own?

**Comment by Hargat** [comment]
Well, if I will change code, I should commit here, and get accept fo commit. Because I need this for team, and we using npm.
When I change prefix by changing "prefix" config, it change only prefix for "include", not for variables!
I this plugin to create JS templates, and using $$ instead of @@ will help me to avoid incpection problems

**Comment by Hargat** [comment]
And in plugin code, in variable.js, there is check of prefix. But somehow it doesn't works on variables

**Comment by Hargat** [comment]
Sorry, looks like it doesn't works with $$, but works with __
